(
 ("default"   . ((user-emacs-directory . "~/emacsConfig/spacemacs.develop")
                 (env . (("SPACEMACSDIR" . "~/emacsConfig/spacemacs.d")))))
 ("spacemacs" . ((user-emacs-directory . "~/emacsConfig/spacemacs.develop")
                 (env . (("SPACEMACSDIR" . "~/emacsConfig/spacemacs.d")))))
 ("spacemacs0". ((user-emacs-directory . "~/emacsConfig/spacemacs0.develop")
                 (env . (("SPACEMACSDIR" . "~/emacsConfig/spacemacs0.d")))))
 ("emacs" . ((user-emacs-directory . "~/emacsConfig/emacs.d")
             ))
 )
